apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - name: streamlit-port
      protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30851  # เปิดพอร์ตให้เข้าถึงผ่าน http://localhost:30851
